name: injectable_app
description: Injectable lib test

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_modular: ^2.0.1
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.1
  cupertino_icons: ^1.0.0
  injectable: ^1.0.5
  mobx: ^1.2.1+3

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner:
  injectable_generator:
  built_value_generator: ^7.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs